# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fyxC <- function(y, betmat, X, tau) {
    .Call('_qrme_fyxC', PACKAGE = 'qrme', y, betmat, X, tau)
}

fvC <- function(v, m, pi, mu, sig) {
    .Call('_qrme_fvC', PACKAGE = 'qrme', v, m, pi, mu, sig)
}

fvyxC <- function(v, betmat, m, pi, mu, sig, y, x, tau) {
    .Call('_qrme_fvyxC', PACKAGE = 'qrme', v, betmat, m, pi, mu, sig, y, x, tau)
}

mh_mcmc_innerC <- function(startval, iters, burnin, drawsd, betmat, m, pi, mu, sig, y, x, tau) {
    .Call('_qrme_mh_mcmc_innerC', PACKAGE = 'qrme', startval, iters, burnin, drawsd, betmat, m, pi, mu, sig, y, x, tau)
}

imp_sampC <- function(Y, X, V, iters, drawsd, betmat, m, pi, mu, sig, tau) {
    .Call('_qrme_imp_sampC', PACKAGE = 'qrme', Y, X, V, iters, drawsd, betmat, m, pi, mu, sig, tau)
}

mh_mcmcC <- function(Y, X, startval, iters, burnin, drawsd, betmat, m, pi, mu, sig, tau) {
    .Call('_qrme_mh_mcmcC', PACKAGE = 'qrme', Y, X, startval, iters, burnin, drawsd, betmat, m, pi, mu, sig, tau)
}

fYXmatC <- function(Y, betmat, X, tau) {
    .Call('_qrme_fYXmatC', PACKAGE = 'qrme', Y, betmat, X, tau)
}

interpolateC <- function(x, y, xval, extrapolate) {
    .Call('_qrme_interpolateC', PACKAGE = 'qrme', x, y, xval, extrapolate)
}

interpolateMatC <- function(x, ymat, xval, extrapolate) {
    .Call('_qrme_interpolateMatC', PACKAGE = 'qrme', x, ymat, xval, extrapolate)
}

computeFytXC <- function(yvals, tvals, Qyxpreds, Ftxpreds, tau, copula, copParam) {
    .Call('_qrme_computeFytXC', PACKAGE = 'qrme', yvals, tvals, Qyxpreds, Ftxpreds, tau, copula, copParam)
}

testCopula <- function(u, v, copParam) {
    .Call('_qrme_testCopula', PACKAGE = 'qrme', u, v, copParam)
}

